### ISSUE TITLE
Bug: translate method can return a JS Object in some cases, where a String is always expected

### ISSUE THREAD

**Issue by eugenet8k** [fnando/i18n#15]
## Description

If `i18n.translate(scope)` does not target a leaf node the return is an object. This generally is useless in the UI, in this case, it would be better to return a standard missing translation string.

## How to reproduce

```js
const i18n = new I18n({en: {labels: {a: "A"}}})
console.log(i18n.translate('labels'))
```

Output:
```
[object Object]
```

## What do you expect

Ideally, it should be claimed as missing translation and processed via a missing translation strategy. So for a default case of using `message` strategy, it would be expected to get a string:

```
[missing "en.labels" translation]
``` 

## What happened instead

An object was returned, despite the original intent of always returning a string from `translate` method. As per the source code

https://github.com/fnando/i18n/blob/60bb7f810c59e9a40ad349021855a8175210dbb0/src/I18n.ts#L379

## Software:

"i18n-js": "4.0.0-alpha.14"

**Comment by eugenet8k** [comment]
For anyone struggling with this, a workaround would be:

```js

export class PatchedI18n extends I18n {
  translate(...args) {
    const translation = super.translate(...args)
    return typeof translation === 'object'
      ? this.missingTranslation.get(...args)
      : translation
  }
}

```

**Comment by fnando** [comment]
Returning _anything_ that exists on a given path is the expected behavior (including v3). The code you mentioned on https://github.com/fnando/i18n/blob/60bb7f810c59e9a40ad349021855a8175210dbb0/src/I18n.ts#L379 is only applicable if options include `count`, which means that the translation is likely to be a pluralization translation (i.e. contain the keys `one`, `other`, `zero`, etc).
